config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'welcome/index'

  resources :workouts do
    resources :stations do
	  resources :exercises
    end
  end

  resources :exercises
  resources :exercise_instances

  root 'welcome#index'
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
	has_many :exercise_instances, dependent: :destroy
	has_many :stations, through: :exercise_instances

	before_save :uppercase_name

	private

	  # Uppercases entire name string
	  def uppercase_name
	    self.name = name.split.map(&:capitalize).join(' ')
	  end
end

app/models/exercise_instance.rb
class ExerciseInstance < ActiveRecord::Base
	belongs_to :station
 	belongs_to :exercise
 	validates :station_id, presence: true
	validates :exercise_id, presence: true
	default_scope {order('exercise_instances.created_at asc')}
end

app/models/station.rb
class Station < ActiveRecord::Base
  belongs_to :workout
  has_many :exercise_instances, dependent: :destroy
  has_many :exercises, through: :exercise_instances
  default_scope {order('stations.created_at asc')}

  before_save :uppercase_name

  private

    # Uppercases entire name string
    def uppercase_name
      self.name = name.split.map(&:capitalize).join(' ')
      self.location = location.split.map(&:capitalize).join(' ')
    end
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { email.downcase! }
	validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

	has_secure_password                    
	validates :password, length: { minimum: 6 }
end

app/models/workout.rb
class Workout < ActiveRecord::Base
	has_many :stations, dependent: :destroy
	validates :name, presence: true, length: { minimum: 5 }

	before_save :uppercase_name

	private

	  # Uppercases entire name string
	  def uppercase_name
	    self.name = name.split.map(&:capitalize).join(' ')
	    self.location = location.split.map(&:capitalize).join(' ')
	  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercise_instance_controller.rb
class ExerciseInstanceController < ApplicationController
  def new
  	@exercise_instance = ExerciseInstance.new
  end

  def create
  	@exercise_instance = ExerciseInstance.new(exercise_instance_params)
  	@exercise_instance.save
  	redirect_to workout_path(@exercise_instance.station.workout.id)
  end

  private 

  	def exercise_instance_params
			params.require(:exercise_instance).permit(:station_id, :exercise_id)
		end
end

app/controllers/exercise_instances_controller.rb
class ExerciseInstancesController < ApplicationController

  def create
  	@exercise_instance = ExerciseInstance.new(exercise_instance_params)
  	@exercise_instance.save
  	redirect_to workout_path(@exercise_instance.station.workout.id)
  end

  private 

  	def exercise_instance_params
			params.require(:exercise_instance).permit(:station_id, :exercise_id)
		end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

	def new
	  @exercise = Exercise.new
	end

	def create
	  @exercise = Exercise.new(exercise_params)

	  if @exercise.save
	  	redirect_to exercises_path
	  else
	    render 'new'
	  end
	end

	def show
	  @exercise = Exercise.find(params[:id])
	end

	def edit
	  @exercise = Exercise.find(params[:id])
	end

	def update
		@exercise = Exercise.find(params[:id])

		if @exercise.update(exercise_params)
				redirect_to exercises_path
		else
				render 'edit'
		end
	end

	def destroy
	  @exercise = Exercise.find(params[:id])
	  @exercise.destroy

	  redirect_to exercises_path
	end

	def index
	  @exercises = Exercise.all
	end

	private

		def exercise_params
			params.require(:exercise).permit(:name)
		end

end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
	def create
		@workout = Workout.find(params[:workout_id])
		@station = @workout.stations.create(station_params)
		redirect_to workout_path(@workout)
	end

	def destroy
		@workout = Workout.find(params[:workout_id])
		@station = @workout.stations.find(params[:id])
		@station.destroy
		redirect_to workout_path(@workout)
	end

	private

		def station_params
			params.require(:station).permit(:name, :location)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

	def new
	  @workout = Workout.new
	end

	def create
	  @workout = Workout.new(workout_params)

	  if @workout.save
	  	redirect_to @workout
	  else
	    render 'new'
	  end
	end

	def show
	  @workout = Workout.find(params[:id])
	  @used_exercises = Array.new
	  @workout.stations.each do |station|
	  	@used_exercises.concat station.exercises.map{|x| x.id}
	  end
	  if @used_exercises.any?
	  	@unused_exercises = Exercise.order('name ASC').where('id NOT IN (?)',@used_exercises)
	  else
	  	@unused_exercises = Exercise.order('name ASC')
	  end
	  @new_exercise_instance = ExerciseInstance.new
	end

	def edit
	  @workout = Workout.find(params[:id])
	end

	def update
 		@workout = Workout.find(params[:id])

		if @workout.update(workout_params)
   			redirect_to @workout
 		else
   			render 'edit'
 		end
	end

	def destroy
	  @workout = Workout.find(params[:id])
	  @workout.destroy

	  redirect_to workouts_path
	end

	def index
	  @workouts = Workout.all
	end

	private

		def workout_params
			params.require(:workout).permit(:name, :location)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercise_instance_helper.rb
module ExerciseInstanceHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercise_instance/_form.html.erb
<%= form_for @new_exercise_instance do |f| %>
	<%= f.hidden_field :station_id, :value => station.id %>
	<p>
		<%= f.collection_select :exercise_id, @unused_exercises,:id,:name, {}, {:class=>'fullLength'} %>
	</p>
	<p>
	  <%= f.submit 'Add Exercise' %>
	</p>
<% end %>  

app/views/exercise_instance/create.html.erb
<h1>ExerciseInstance#create</h1>
<p>Find me in app/views/exercise_instance/create.html.erb</p>

app/views/exercise_instance/new.html.erb
<h1>ExerciseInstance#new</h1>
<p>Find me in app/views/exercise_instance/new.html.erb</p>

app/views/exercises/_exercise.html.erb
<p>
	<strong>Name:</strong>
	<%= exercise.name %>
</p>

<p>
  <%= link_to 'Destroy Exercise', [exercise.station, exercise],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/exercises/_form.html.erb
<%= form_for @exercise do |f| %>
  <% if @exercise.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited
      this exercise from being saved:</h2>
    <ul>
    <% @exercise.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing exercise</h1>

<%= render 'form' %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/index.html.erb
<h1>Exercises</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>

  <% @exercises.each do |exercise| %>
    <tr>
      <td><%= exercise.name %></td>
      <td><%= link_to 'Show', exercise_path(exercise) %></td>
   	  <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
      <td><%= link_to 'Destroy', exercise_path(exercise), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New exercise', new_exercise_path %>

app/views/exercises/new.html.erb
<h1>New Exercise</h1>

<%= render 'form' %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @exercise.name %>
</p>

<%= link_to 'Back', exercises_path %>
| <%= link_to 'Edit', edit_exercise_path(@exercise) %>

app/views/layouts/_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58924810-1', 'circuitsequence.com');
  ga('send', 'pageview');
</script>

app/views/layouts/_google_adsense.html.erb
<!-- <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script> -->
<!-- Circuit Sequence Main -->
<!-- <ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-6083282077361779"
     data-ad-slot="3548312530"
     data-ad-format="auto"></ins> -->
<!-- <script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script> -->

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58924810-1', 'circuitsequence.com');
  ga('send', 'pageview');
</script>

app/views/layouts/_header_navigation.html.erb
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to 'Circuit Sequence', welcome_index_path, class: "navbar-brand" %>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li><%= link_to 'Workouts', workouts_path %></li>
				<li><%= link_to 'Exercises', exercises_path %></li>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Circuit Sequence</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header_navigation' %>
	<% if Rails.env.production? %>
		<%= render 'layouts/google_adsense' %>
	<% end %>
	<div class="container">
		<%= yield %>
	</div>
</body>
<% if Rails.env.production? %>
	<%= render 'layouts/google_analytics' %>
<% end %>
</html>

app/views/stations/_exercise_instance.html.erb
<p>
	<li><%= exercise.name %></li>
</p>

app/views/stations/_form.html.erb
<%= form_for([@workout, @workout.stations.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'fullLength' %>
  </p>
  <p>
    <%= f.label :location %><br>
    <%= f.text_field :location, class: 'fullLength' %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>  

app/views/stations/_station.html.erb
<div class="station well">
	
	<h3><%= station.name %></h3>

	<h4>
		<strong>Location:</strong>
		<%= station.location %>
	</h4>

	<% if station.exercises.any? %>
		<hr />
		
		<h4>Exercises</h4>
		<ol>
			<%= render partial: "stations/exercise_instance", collection: station.exercises, :as => :exercise %>
		</ol>
	<% end %>

	<hr />

	<h4>Add an Exercise</h4>
	<% if @unused_exercises.any? %>
		<%= render 'exercise_instance/form', station: station %>
	<% else %>
		<em>no unused exercises to choose from. Please add more exercises <%= link_to 'Here', new_exercise_path %></em>
	<% end %>

	<p>
	  <%= link_to 'Destroy Station', [station.workout, station],
	               method: :delete,
	               data: { confirm: 'Are you sure?' } %>
	</p>	
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/welcome/index.html.erb
<h1>Circuit Sequence</h1>

<p>
	Welcome to Circuit Sequence-- The World's most unfinished workout planning application.
</p>

<p>
	This app was built as a proof of concept. It proves that, A) there is a better way to organize workouts than pen and paper, and, B) that I can build a reasonably functional rails app. The primary motivation was simply so that I could lean Rails and write <a target="_blank" href="http://prgrmmr.com">a blog about it</a>.
</p>


<h3>The core functionality was planned as follows:</h3>
<ol>
	<li>You input your regular exercises. An exercise represents a single, typically repeatable, action which you plan to perform during the course of a workout.</li>
	<li>You plan a workout. A workout represents a specific period of time in which you plan to move your body to generate sweat and frustration.</li>
	<li>Your workout contains stations. A station represents either a physical location or logical grouping of exercises you plan to perform, in order.</li>
	<li>Lastly, each station contains a reference to one or more of your predefined exercises. Exercises within stations are ordered, and can be re-ordered simply.</li>
</ol>

<p>
	If you're interested in chatting about this app, you can reach out to me on twitter @theprgrmmr or read about its making on <a target="_blank" href="http://prgrmmr.com">http://prgrmmr.com</a>.
</p>

app/views/workouts/_form.html.erb
<%= form_for @workout do |f| %>
  <% if @workout.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@workout.errors.count, "error") %> prohibited
      this workout from being saved:</h2>
    <ul>
    <% @workout.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/workouts/edit.html.erb
<h1>Editing Workout</h1>

<%= render 'form' %>

<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<h1>Workouts</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th colspan="3"></th>
  </tr>

  <% @workouts.each do |workout| %>
    <tr>
      <td><%= workout.name %></td>
      <td><%= workout.location %></td>
      <td><%= link_to 'Show', workout_path(workout) %></td>
   	  <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
      <td><%= link_to 'Destroy', workout_path(workout), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New workout', new_workout_path %>

app/views/workouts/new.html.erb
<h1>New Workout</h1>

<%= render 'form' %>

<%= link_to 'Back', workouts_path %>

app/views/workouts/show.html.erb
<h1><%= @workout.name %></h1>

<h4>
  <strong>Location:</strong>
  <%= @workout.location %>
</h4>

<h4>
  <strong>Date:</strong>
</h4>

<div class="whiteWell">
	<% if @workout.stations.any? %>
		<h2>Stations</h2>
		<%= render @workout.stations %>
	<% end %>
	
	<div id="addStationWrapper" class="station well">
		<h4>Add a station</h4>
		<%= render "stations/form" %>
	</div>
</div>

<%= link_to 'Back', workouts_path %>
| <%= link_to 'Edit', edit_workout_path(@workout) %>